### ISSUE TITLE
Appointments can be set too close to current time

### ISSUE THREAD

**Issue by jmpfar** [avishail/my-visit#5]
Hi, very cool project!

I tried it out and got an appointment for today in 10 minutes, which was a bit too early for me to get to a different city :D
Due to issues in myvisit with cancelling a too close appointment, I couldn't cancel the appointment and now I'm banned from setting a new appointment for who knows how long

In the mean time I wrote some code to get around it, however it's too custom for my use case and it would probably need some question in the UI or a different default

I'm sharing it here, feel free to use it if you want:

```javascript
function isToday(calendarDate) {
    const date = new Date(calendarDate);
    const now = new Date();

    return date.setHours(0, 0, 0, 0) === now.setHours(0, 0, 0, 0);
}

function hasEnoughTimeToGetThere(calendarDate, timeslot) {
    if (!isToday(calendarDate)) {
        return true;
    }

    let time = new Date();
    time.setHours(0,0,0,0);
    time.setMinutes(timeslot);

    const now = new Date();
    const MINIMUM_HOURS_AWAY = 3;

    const hourDiff = (time - now) / 60 / 60 / 1000;
    return hourDiff >= MINIMUM_HOURS_AWAY;
}

async function getRelevantTimeSlots(serviceId, calendarDate, calendarId) {

[...]

    return json['Results'].filter(slot => {
        if (!hasEnoughTimeToGetThere(calendarDate, slot['Time'])) {
            console.log(`Not enough time to get there ... date=${calendarDate}, slot=${slot['Time']}`)
            return false;
        }

        if (!timeSelection.length) {
            return true;
        }

[...]

```

**Comment by avishail** [comment]
Hi @jmpfar and thanks for your comment. I've encountered the same problem and was planning on fixing this. I'll integrate it soon.

I'm curios, how did you come across this repo? I didn't publish this anywhere.

**Comment by jmpfar** [comment]
I searched github for "myvisit.com" expecting others to have shared my woes, and then saw someone wrote something 2 weeks ago :)

**Comment by avishail** [comment]
@jmpfar 

I've merged the fix: https://github.com/avishail/my-visit/pull/6

not exactly as you implemented it but it follows the same logic.

BTW, feel free to tell your friends about Shraga. I won't make a public announcement about it because:

1. it is against the term of use of my-visit and I don't want to get into troubles with them.
2. the more users to use this, the less effective it will become.

P.S Thanks for the coffee :)

**Comment by jmpfar** [comment]
Thanks!
Btw, just saw on twitter that someone is developing another extension https://twitter.com/shilomagen/status/1637507295914459139
